### ISSUE TITLE
Custom Templates not loaded

### ISSUE THREAD

**Issue by Skinwalker** [yireo/Yireo_EmailOverride#21]
I installed the extension.

Copied the order_new.html from

```
app/locale/de_DE/template/email/sales
```

to

```
app/design/frontend/juts/default/locale/de_DE/template/email/sales/order_new.html
```

but when I try to make changes I don't see them in the E-Mail nor on the Preview via Email Tester.

Any idea why?

**Comment by jissereitsma** [comment]
No ideas why. Could you walk us down the list of things you have done already, so that we can confirm what you have done to make this work? For instance, are you sure that de_DE is indeed configured as locale for the Store View that is used to send this mail? Also, flushing cache is done. Checks for zero errors in the Magento logs, while debugging?

You mention the EmailTester: Can you also confirm that this test was done with the Store View "German" (de_DE) selected in the EmailTester backend?

**Comment by Skinwalker** [comment]
Found out that the language file override works.

I will make some more tests - maybe just the files in den subfolders, like template/email/sales are not working.

**Comment by jissereitsma** [comment]
Closing this for now, because there has been no response for various months now, and because the issue was never confirmed either.
