### ISSUE TITLE
Yireo to work togheter with Fooman Attachments

### ISSUE THREAD

**Issue by dutyhook** [yireo/Yireo_EmailOverride#32]
As Yireo provides options of templates in local folder and custom translation I use for years already. Very good and reliable extension. Now wanted to add Fooman attachments. But they both seem to rewrite the same model on some level.

YIREO config
( https://github.com/yireo/Yireo_EmailOverride )
rewrite
email_template>Yireo_EmailOverride_Model_Email_Template</email_template
/rewrite

FOOMAN config
rewrite
email_template_mailer>Fooman_EmailAttachments_Model_Core_Email_Template_Mailer</email_template_mailer
/rewrite

As a result, all emails without attachment use local folder templates and emails with attachment use default ones. Is there any reasonable way to set these to work together?

**Comment by jissereitsma** [comment]
This has been possibly fixed by the latest release, by adding new lines to the following file. https://github.com/yireo/Yireo_EmailOverride/blob/master/source/app/code/community/Yireo/EmailOverride/Model/Email/Template/Compatibility.php Please note that open source is not freeware, but a way of working together on sources and you are welcome to submit PRs.
