### ISSUE TITLE
Magento 1.8.1 and Design/Fallback.php

### ISSUE THREAD

**Issue by langsweirdt** [yireo/Yireo_EmailOverride#8]
I've installed he EmailOverride extension in my 1.8.1 installation, but things 'are not working' (as in, the default/core email templates are always selected).

I did some debugging and see the following in the logs:

```
2015-03-29T19:39:31+00:00 ERR (3): Warning: include(): Failed opening 'Mage/Core/Model/Design/Fallback.php' for inclusion (include_path='/vagrant/site/app/code/local:/vagrant/site/app/code/community:/vagrant/site/app/code/core:/vagrant/site/lib:.:/usr/share/php:/usr/share/pear')  in /vagrant/site/lib/Varien/Autoload.php on line 93
```

As far as I can tell, this is generated by function _loadThemeTranslation in Translate.php.

```
$fallbackModel = Mage::getModel('core/design_fallback');). 
```

Looking at the Magento 1.8.1 source code, there is no file Design/Fallback.php, so it makes sense it cannot be loaded.
After this, the getTemplateFile function isn't even called.

However, I don't know if this is the reason of my problems or how I can proceed... any help would be much appreciated.

Thanks.

**Comment by yireo** [comment]
Thanks for reporting this. I've just tested this myself under Magento 1.8.1 and in my case this is working without issues. Perhaps you can share information on the usage of the paths of your template files and which theming settings you are using? Because currently, it does not seem to be an issue related with Magento 1.8 but related to your specific environment only. The PHP Warning is intended and can be disgarded. Under Magento 1.7 you'll get the same, but our extension works there as well. If you want us to dive in and solve this for you, please mail us at info@yireo.com

**Comment by langsweirdt** [comment]
I have the following theme installed:
http://themeforest.net/item/porto-ultimate-responsive-magento-theme/9725864
As well as the ASchroder extension.
However, I did not follow the procedure as stated in the FAQ on this page: https://www.yireo.com/software/magento-extensions/email-override
Because I see the Template.php file in the module now has a wrapper to automatically override the correct base class.
I didn't do anything else but add the proper folders and files below design/frontent..

Knowing that the problem is specific to my setup, I'll have another shot. If I can't find it, I'll mail you.
Thank you for your response.

**Comment by jissereitsma** [comment]
As far as I know, this issue has been fixed already by adding support to the various extensions in EmailOverride.
